name: Add Server Time

on:
  workflow_dispatch: # 允许手动触发此工作流
  schedule:
  # 每天每隔4小时执行一次，所有时间都是 UTC 时间。
  # 目标首次点击时间为服务器所在地时间 04:30，假设服务器所在地是 UTC+3 时区。
  # 因此 04:30 (UTC+3) 对应 UTC 时间为 01:30。
  - cron: '30 1 * * *'  # UTC 01:30 (服务器所在地时间 04:30)
  - cron: '30 5 * * *'  # UTC 05:30 (服务器所在地时间 08:30)
  - cron: '30 9 * * *'  # UTC 09:30 (服务器所在地时间 12:30)
  - cron: '30 13 * * *' # UTC 13:30 (服务器所在地时间 16:30)
  - cron: '30 17 * * *' # UTC 17:30 (服务器所在地时间 20:30)
  - cron: '30 21 * * *' # UTC 21:30 (服务器所在地时间 00:30, 次日)

jobs:
  add_time:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境上运行

    steps:
      - name: Checkout repository # 获取你的代码
        uses: actions/checkout@v4

      - name: Set up Python # 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 使用最新的 Python 3 版本

      - name: Install Playwright and dependencies # 安装 Playwright 及其浏览器依赖
        run: |
          pip install playwright
          playwright install --with-deps chromium # 安装 Chromium 浏览器及其运行所需依赖

      - name: Run Time Adder Script # 运行 Python 脚本
        env:
          # 从 GitHub Secrets 读取环境变量。请在你的仓库设置中配置这些 Secrets。
          # 优先使用 REMEMBER_WEB_COOKIE。如果有效，可绕过邮箱密码登录。
          REMEMBER_WEB_COOKIE: ${{ secrets.REMEMBER_WEB_COOKIE }}
          # 如果 REMEMBER_WEB_COOKIE 无效或未设置，则使用以下邮箱和密码
          PTERODACTYL_EMAIL: ${{ secrets.PTERODACTYL_EMAIL }}
          PTERODACTYL_PASSWORD: ${{ secrets.PTERODACTYL_PASSWORD }}
        run: python main.py
