name: EternalZero Server Auto Renew

on:
  schedule:
    # 每隔3小时运行一次
    # cron表达式：分 时 日 月 周
    # 0 */3 * * * 表示每3小时的0分执行 (例如：00:00, 03:00, 06:00, ...)
    - cron: '0 */3 * * *'
  workflow_dispatch: # 允许手动触发工作流

jobs:
  renew_server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 可以选择其他版本，如3.10, 3.11, 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager requests python-dateutil # 安装所需库
        # webdriver_manager 会自动下载对应版本的WebDriver

    - name: Run server auto renew script
      env:
        # 从GitHub Secrets中读取环境变量
        PTERODACTYL_SESSION: ${{ secrets.PTERODACTYL_SESSION }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python eternalzero_renew.py
