name: EternalZero Server Auto Renew

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 每3小时运行一次 (UTC时间)
    # 您可以根据需要调整cron表达式
    # 例如: '0 */3 * * *' 表示每3小时的0分钟运行
    # 首次运行请在本地或通过手动触发验证
    - cron: '0 */3 * * *' 

jobs:
  renew-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的Python 3版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests webdriver_manager # 添加 webdriver_manager

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable # 安装稳定版 Chrome

    - name: Run renewal script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PTERODACTYL_SESSION: ${{ secrets.PTERODACTYL_SESSION }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python eternalzero_renew.py
